name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tester

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyserial pylint

      - name: Lint Python files
        run: |
          pylint fuzzer.py serial_comm.py || true

      - name: Run Python unit tests (if available)
        run: |
          if [ -d "tests" ]; then
            python -m unittest discover -s tests
          else
            echo "No test directory found, skipping unit tests."
          fi
